export const userAction = {
    SET_USER_DETAILS: 'USER.SET_USER_DETAILS',
    FOLLOWED: 'USER.FOLLOWED',
    UN_FOLLOWED: 'USER.UN_FOLLOWED',
    SET_PROFILE_PHOTO: 'USER.SET_PROFILE_PHOTO',
    LOADING: 'USER.LODAING'
}
