export const postsAction = {
    SET_NEW_POST: 'POSTS.SET_NEW_POST',
    SET_ALL_POSTS: 'POSTS.SET_ALL_POSTS',
    SET_POSTS_BY_CATEGORY: 'POSTS.SET_POSTS_BY_CATEGORY',
    SET_POST_LIKES: 'POSTS.SET_POST_LIKES',
    SET_SINGLE_POST: 'POSTS.SET_SINGLE_POST',
    DELETE_POST: 'POSTS.DELETE_POST',
    LOADING: 'POSTS.LOADING'
}
