export const postsAction = {
    SET_NEW_POST: 'POSTS.SET_NEW_POST',
    SET_ALL_POSTS: 'POSTS.SET_ALL_POSTS',
    SET_POPULAR_POSTS: 'POSTS.SET_POPULAR_POSTS',
    SET_POST_LIKES: 'POSTS.SET_POST_LIKES',
    SET_SINGLE_POST: 'POSTS.SET_SINGLE_POST',
    SET_EDIT_POST: 'POSTS.SET_EDIT_POST',
    DELETE_POST: 'POSTS.DELETE_POST',
    LOADING: 'POSTS.LOADING',
    EDITED_POST: 'POSTS.EDITED_POST'
}
